import type { StoreProduct } from './types';

type DemoProduct = Omit<StoreProduct, 'images'>;

const make = (product: DemoProduct): DemoProduct => product;

export const demoProducts: DemoProduct[] = [
  make({ id: 'demo-w-1', name: 'Rose Heritage Saree', slug: 'rose-heritage-saree', description: 'An elegant saree and blouse combination inspired by timeless Bangladeshi occasion wear.', shortDescription: 'Elegant saree and blouse set.', segment: 'WOMEN', categoryName: 'Saree & Blouse', itemTypeName: 'Traditional Wear', basePrice: 3950, salePrice: 3490, sku: 'TB-W-001', imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=82', sizes: ['Free Size'], colors: ['Rose', 'Maroon'], stock: 24, isFeatured: true, isNewArrival: true, isBestSeller: true }),
  make({ id: 'demo-w-2', name: 'Floral Three-Piece Set', slug: 'floral-three-piece-set', description: 'A graceful three-piece set with polished print and comfortable tailoring.', shortDescription: 'Graceful floral three-piece.', segment: 'WOMEN', categoryName: 'Salwar Kameez & Three-Piece', itemTypeName: 'Traditional Wear', basePrice: 2850, salePrice: 2490, sku: 'TB-W-002', imageUrl: 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=1000&q=82', sizes: ['S', 'M', 'L', 'XL'], colors: ['Pink', 'Teal'], stock: 30, isFeatured: true, isNewArrival: true, isBestSeller: true }),
  make({ id: 'demo-w-3', name: 'Premium Embroidered Kurti', slug: 'premium-embroidered-kurti', description: 'A refined embroidered kurti designed for effortless everyday comfort.', shortDescription: 'Premium embroidered kurti.', segment: 'WOMEN', categoryName: 'Kurtis, Tops & Tunics', itemTypeName: 'Clothing', basePrice: 1750, salePrice: 1490, sku: 'TB-W-003', imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=1000&q=82', sizes: ['S', 'M', 'L', 'XL'], colors: ['Ivory', 'Rose'], stock: 26, isNewArrival: true }),
  make({ id: 'demo-w-4', name: 'Noor Modest Abaya', slug: 'noor-modest-abaya', description: 'A flowing modest abaya with clean detailing and a sophisticated silhouette.', shortDescription: 'Elegant flowing abaya.', segment: 'WOMEN', categoryName: 'Abaya, Hijab & Modest Wear', itemTypeName: 'Dress', basePrice: 3250, salePrice: 2890, sku: 'TB-W-004', imageUrl: 'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=1000&q=82', sizes: ['52', '54', '56', '58'], colors: ['Black', 'Mocha'], stock: 18, isBestSeller: true }),
  make({ id: 'demo-w-5', name: 'Butterfly Occasion Accessory Set', slug: 'butterfly-occasion-accessory-set', description: 'A coordinated fashion accessory set for wedding, party and festive outfits.', shortDescription: 'Occasion accessory set.', segment: 'WOMEN', categoryName: 'Bags, Jewellery & Accessories', itemTypeName: 'Accessory', basePrice: 2250, salePrice: 1890, sku: 'TB-W-005', imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=82', sizes: ['Standard'], colors: ['Gold', 'Blush Pink'], stock: 22 }),

  make({ id: 'demo-m-1', name: 'Classic Eid Panjabi', slug: 'classic-eid-panjabi', description: 'A premium panjabi with a tailored profile and subtle festive detailing.', shortDescription: 'Premium festive panjabi.', segment: 'MEN', categoryName: 'Panjabi & Pajama', itemTypeName: 'Traditional Wear', basePrice: 2950, salePrice: 2590, sku: 'TB-M-001', imageUrl: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?auto=format&fit=crop&w=1000&q=82', sizes: ['M', 'L', 'XL', 'XXL'], colors: ['Navy', 'Ivory'], stock: 24, isFeatured: true, isNewArrival: true, isBestSeller: true }),
  make({ id: 'demo-m-2', name: 'Executive Cotton Shirt', slug: 'executive-cotton-shirt', description: 'A crisp cotton shirt for office meetings and smart-casual evenings.', shortDescription: 'Crisp executive shirt.', segment: 'MEN', categoryName: 'Casual & Formal Shirts', itemTypeName: 'Clothing', basePrice: 1950, salePrice: 1690, sku: 'TB-M-002', imageUrl: 'https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=1000&q=82', sizes: ['M', 'L', 'XL'], colors: ['White', 'Sky Blue'], stock: 28, isFeatured: true, isNewArrival: true }),
  make({ id: 'demo-m-3', name: 'Signature Cotton Polo', slug: 'signature-cotton-polo', description: 'A structured cotton polo with a soft feel and versatile styling.', shortDescription: 'Signature cotton polo.', segment: 'MEN', categoryName: 'T-Shirts & Polo Shirts', itemTypeName: 'Clothing', basePrice: 1550, salePrice: 1290, sku: 'TB-M-003', imageUrl: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?auto=format&fit=crop&w=1000&q=82', sizes: ['M', 'L', 'XL', 'XXL'], colors: ['Black', 'White'], stock: 32, isFeatured: true, isNewArrival: true, isBestSeller: true }),
  make({ id: 'demo-m-4', name: 'Modern Straight-Fit Jeans', slug: 'modern-straight-fit-jeans', description: 'Durable straight-fit jeans with a clean modern profile.', shortDescription: 'Modern straight-fit jeans.', segment: 'MEN', categoryName: 'Pants, Jeans & Trousers', itemTypeName: 'Clothing', basePrice: 2350, salePrice: 1990, sku: 'TB-M-004', imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1000&q=82', sizes: ['30', '32', '34', '36'], colors: ['Indigo', 'Black'], stock: 20 }),
  make({ id: 'demo-m-5', name: 'Gentleman Essentials Set', slug: 'gentleman-essentials-set', description: 'A polished accessories selection for formal and festive looks.', shortDescription: 'Gentleman accessory set.', segment: 'MEN', categoryName: 'Shoes, Watches & Accessories', itemTypeName: 'Accessory', basePrice: 3450, salePrice: 2990, sku: 'TB-M-005', imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1000&q=82', sizes: ['Standard'], colors: ['Black', 'Brown'], stock: 16, isBestSeller: true }),

  make({ id: 'demo-c-1', name: 'Butterfly Bloom Girls Frock', slug: 'butterfly-bloom-girls-frock', description: 'A charming girls frock for birthdays and family events.', shortDescription: 'Charming girls frock.', segment: 'CHILDREN', categoryName: "Girls' Frocks & Dresses", itemTypeName: 'Dress', basePrice: 2050, salePrice: 1750, sku: 'TB-C-001', imageUrl: 'https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=1000&q=82', sizes: ['2Y', '4Y', '6Y', '8Y'], colors: ['Blush Pink', 'Cream'], stock: 18, isFeatured: true, isNewArrival: true, isBestSeller: true }),
  make({ id: 'demo-c-2', name: 'Junior Festive Panjabi', slug: 'junior-festive-panjabi', description: 'A comfortable boys panjabi for celebrations and family gatherings.', shortDescription: 'Comfortable boys panjabi.', segment: 'CHILDREN', categoryName: "Boys' Panjabi & Shirts", itemTypeName: 'Traditional Wear', basePrice: 1850, salePrice: 1590, sku: 'TB-C-002', imageUrl: 'https://images.unsplash.com/photo-1503919545889-aef636e10ad4?auto=format&fit=crop&w=1000&q=82', sizes: ['2Y', '4Y', '6Y', '8Y'], colors: ['Blue', 'White'], stock: 20, isNewArrival: true }),
  make({ id: 'demo-c-3', name: 'Soft Newborn Romper Set', slug: 'soft-newborn-romper-set', description: 'A soft and gentle romper set designed for newborn comfort.', shortDescription: 'Soft newborn romper set.', segment: 'CHILDREN', categoryName: 'Baby Clothing', itemTypeName: 'Clothing', basePrice: 1250, salePrice: 1090, sku: 'TB-C-003', imageUrl: 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=1000&q=82', sizes: ['0-3M', '3-6M', '6-12M'], colors: ['White', 'Pastel Pink'], stock: 24 }),
  make({ id: 'demo-c-4', name: 'Little Celebration Outfit', slug: 'little-celebration-outfit', description: 'A picture-perfect traditional outfit for special moments.', shortDescription: 'Kids celebration outfit.', segment: 'CHILDREN', categoryName: 'Kids Party & Traditional Wear', itemTypeName: 'Traditional Wear', basePrice: 2550, salePrice: 2190, sku: 'TB-C-004', imageUrl: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=1000&q=82', sizes: ['2Y', '4Y', '6Y', '8Y'], colors: ['Ivory', 'Pink'], stock: 16, isBestSeller: true }),
  make({ id: 'demo-c-5', name: 'Kids Adventure Essentials', slug: 'kids-adventure-essentials', description: 'A practical kids accessory choice for school and outings.', shortDescription: 'Kids adventure accessories.', segment: 'CHILDREN', categoryName: 'Kids Footwear, Bags & Accessories', itemTypeName: 'Accessory', basePrice: 1750, salePrice: 1490, sku: 'TB-C-005', imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=82', sizes: ['Standard'], colors: ['Pink', 'Navy'], stock: 20 }),
];
